# .github/workflows/watch.yml
name: JS Puzzle Watch
on:
  schedule:
    - cron: "*/5 * 1,2 * *"
  workflow_dispatch: {}
jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - env: { APPRISE_URLS: ${{ secrets.APPRISE_URLS }} }
        run: python watcher.py
