name: JS Puzzle Watch

on:
  schedule:
    - cron: "*/6 * * * *" 
  workflow_dispatch: {} 

jobs:
  watch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run watcher
        env:
          APPRISE_URLS: ${{ secrets.APPRISE_URLS }}
        run: python watch.py
